# Generated by Django 2.2.5 on 2019-09-28 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(default='', max_length=50)),
                ('venue_streetnum', models.IntegerField(blank=True, default=0)),
                ('venue_street', models.CharField(default='', max_length=50)),
                ('venue_suburb', models.CharField(default='', max_length=50)),
                ('venue_postcode', models.IntegerField(default='')),
                ('venue_website', models.URLField(default='', max_length=100)),
                ('venue_email', models.CharField(default='', max_length=50)),
                ('venue_photo', models.ImageField(blank=True, upload_to='media/venue_photos')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='', max_length=50)),
                ('event_description', models.CharField(default='', max_length=500)),
                ('event_start_datetime', models.DateTimeField(verbose_name='start time and date')),
                ('event_end_datetime', models.DateTimeField(verbose_name='end time and date')),
                ('event_photo', models.ImageField(blank=True, upload_to='media/event_photos')),
                ('event_venue', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='PoorEvents.Venue')),
            ],
        ),
    ]
