# Generated by Django 2.2.5 on 2019-09-28 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(default='', max_length=50)),
                ('venue_address', models.CharField(default='', max_length=500)),
                ('venue_phone', models.FloatField(default='0')),
                ('venue_email', models.CharField(default='', max_length=50)),
                ('venue_photo', models.ImageField(null=True, upload_to='media/venue_photos')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='', max_length=50)),
                ('event_description', models.CharField(default='', max_length=500)),
                ('event_start_datetime', models.DateTimeField(verbose_name='start time and date')),
                ('event_end_datetime', models.DateTimeField(verbose_name='end time and date')),
                ('event_photo', models.ImageField(null=True, upload_to='media/event_photos')),
                ('event_venue', models.ManyToManyField(to='PoorEvents.Venue')),
                ('host', models.ForeignKey(null='True', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
