# Generated by Django 2.2.5 on 2019-09-28 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PoorEvents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
