# Generated by Django 2.2.5 on 2019-09-30 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PoorEvents', '0002_auto_20190930_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEventPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_category', models.ManyToManyField(default='', to='PoorEvents.Category')),
                ('fav_events', models.ManyToManyField(default='', to='PoorEvents.Event')),
                ('fav_venues', models.ManyToManyField(default='', to='PoorEvents.Venue')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='userpreferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
