# Generated by Django 2.2.5 on 2019-09-29 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PoorEvents', '0003_event_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='category',
        ),
    ]
