# Generated by Django 2.2.5 on 2019-09-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PoorEvents', '0004_auto_20190929_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='categories',
            new_name='category',
        ),
    ]
