# Generated by Django 2.2.5 on 2019-09-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoorUsers', '0006_auto_20190929_1825'),
        ('PoorEvents', '0005_auto_20190929_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(default='', to='PoorUsers.UserProfile', verbose_name='attendees'),
        ),
    ]
