# Generated by Django 2.2.5 on 2019-09-29 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoorEvents', '0006_event_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(default='', related_name='atendees', to=settings.AUTH_USER_MODEL, verbose_name='attendees'),
        ),
    ]
