# Generated by Django 2.2.5 on 2019-09-29 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoorEvents', '0007_auto_20190929_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(default='', related_name='attendees', to=settings.AUTH_USER_MODEL),
        ),
    ]
