# Generated by Django 2.2.5 on 2019-09-29 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PoorUsers', '0004_auto_20190929_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='favourite_categories',
            new_name='category',
        ),
    ]
